-- 000001_init.down.sql
DROP FUNCTION IF EXISTS public.set_updated_at();
DROP SCHEMA IF EXISTS estoque CASCADE;
DROP SCHEMA IF EXISTS vendas CASCADE;
DROP SCHEMA IF EXISTS compras CASCADE;
DROP SCHEMA IF EXISTS catalogo CASCADE;
DROP SCHEMA IF EXISTS fornecedores CASCADE;
DROP SCHEMA IF EXISTS clientes CASCADE;
DROP SCHEMA IF EXISTS iam CASCADE;
